-- Uses only the 16 console palette slots, so it follows whichever theme
-- tty-theme or xinitrc loaded. Backgrounds stay in slots 0-7 because tmux on
-- the Linux console cannot draw bright backgrounds.
vim.cmd.highlight('clear')
vim.g.colors_name = 'tty16'
vim.o.background = 'dark'

local groups = {
  Normal = {},
  NormalFloat = {},
  FloatBorder = { ctermfg = 8 },
  FloatTitle = { ctermfg = 4, bold = true },
  Comment = { ctermfg = 8, italic = true },
  Constant = { ctermfg = 5 },
  String = { ctermfg = 2 },
  Character = { ctermfg = 2 },
  Identifier = { ctermfg = 7 },
  Function = { ctermfg = 4 },
  Statement = { ctermfg = 1 },
  Operator = { ctermfg = 7 },
  PreProc = { ctermfg = 6 },
  Type = { ctermfg = 3 },
  Special = { ctermfg = 6 },
  Delimiter = { ctermfg = 7 },
  Title = { ctermfg = 4, bold = true },
  Underlined = { ctermfg = 4, underline = true },
  Todo = { ctermfg = 0, ctermbg = 3, bold = true },
  Error = { ctermfg = 1, bold = true },

  ['@variable'] = { ctermfg = 7 },
  ['@variable.builtin'] = { ctermfg = 5 },
  ['@property'] = { ctermfg = 12 },
  ['@constructor'] = { ctermfg = 3 },
  ['@module'] = { ctermfg = 6 },
  ['@tag'] = { ctermfg = 4 },
  ['@tag.attribute'] = { ctermfg = 3 },
  ['@markup.heading'] = { ctermfg = 4, bold = true },
  ['@markup.raw'] = { ctermfg = 2 },
  ['@markup.link.url'] = { ctermfg = 6, underline = true },
  ['@markup.list'] = { ctermfg = 1 },
  ['@markup.strong'] = { bold = true },
  ['@markup.italic'] = { italic = true },

  LineNr = { ctermfg = 8 },
  CursorLineNr = { ctermfg = 3, bold = true },
  CursorLine = {},
  SignColumn = {},
  FoldColumn = { ctermfg = 8 },
  Folded = { ctermfg = 8 },
  NonText = { ctermfg = 8 },
  Whitespace = { ctermfg = 8 },
  SpecialKey = { ctermfg = 8 },
  EndOfBuffer = { ctermfg = 8 },
  WinSeparator = { ctermfg = 8 },
  StatusLine = { ctermfg = 0, ctermbg = 4 },
  StatusLineNC = { ctermfg = 8 },
  TabLine = { ctermfg = 8 },
  TabLineFill = {},
  TabLineSel = { ctermfg = 0, ctermbg = 4, bold = true },
  Visual = { ctermfg = 0, ctermbg = 4 },
  Search = { ctermfg = 0, ctermbg = 3 },
  CurSearch = { ctermfg = 0, ctermbg = 6, bold = true },
  IncSearch = { ctermfg = 0, ctermbg = 6, bold = true },
  MatchParen = { ctermfg = 3, bold = true },
  Pmenu = {},
  PmenuSel = { ctermfg = 0, ctermbg = 4 },
  PmenuSbar = {},
  PmenuThumb = { ctermbg = 7 },
  QuickFixLine = { ctermfg = 6, bold = true },
  Directory = { ctermfg = 4 },
  Question = { ctermfg = 2 },
  MoreMsg = { ctermfg = 2 },
  ModeMsg = { bold = true },
  WarningMsg = { ctermfg = 3 },
  ErrorMsg = { ctermfg = 1, bold = true },

  Added = { ctermfg = 2 },
  Changed = { ctermfg = 3 },
  Removed = { ctermfg = 1 },
  DiffAdd = { ctermfg = 2 },
  DiffChange = { ctermfg = 3 },
  DiffDelete = { ctermfg = 1 },
  DiffText = { ctermfg = 0, ctermbg = 3 },

  DiagnosticError = { ctermfg = 1 },
  DiagnosticWarn = { ctermfg = 3 },
  DiagnosticInfo = { ctermfg = 4 },
  DiagnosticHint = { ctermfg = 6 },
  DiagnosticOk = { ctermfg = 2 },
  DiagnosticUnderlineError = { underline = true },
  DiagnosticUnderlineWarn = { underline = true },
  DiagnosticUnderlineInfo = { underline = true },
  DiagnosticUnderlineHint = { underline = true },
  SpellBad = { ctermfg = 1, underline = true },
  SpellCap = { ctermfg = 3, underline = true },
  SpellRare = { ctermfg = 5, underline = true },
  SpellLocal = { ctermfg = 6, underline = true },

  TelescopeMatching = { ctermfg = 3, bold = true },
  TelescopePromptPrefix = { ctermfg = 4 },
  TelescopeSelectionCaret = { ctermfg = 0, ctermbg = 4 },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
