set show_hidden true
set preview_files true
set preview_directories true
set use_preview_script false
set draw_borders both
set vcs_aware true
set colorscheme default
map gh cd ~
map gp cd ~/projects
map E shell nvim %f
map G shell lazygit
map zf fzf_select
