has w3m, mime ^text/html = w3m -- "$@"
mime ^text, has nvim = nvim -- "$@"
ext (json|md|toml|yaml|yml|lua|sh|py|js|jsx|ts|tsx|html|css|conf|txt)$ = nvim -- "$@"
mime ^audio, has mpv = mpv --no-video -- "$@"
mime ^video, has mpv = mpv -- "$@"
has less = less -- "$@"
